services:
  portainer:
    container_name: portainer
    hostname: portainer
    image: portainer/portainer-ce:latest
    networks:
      - traefik_default
    ports:
      - 9000:9000
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
    - traefik.enable=true
    - traefik.docker.network=traefik_default
    - traefik.http.routers.portainer.entrypoints=websecure
    - traefik.http.routers.portainer.rule=Host(`portainer.domain.com`)
    - traefik.http.services.portainer.loadbalancer.server.port=9000

networks:
  traefik_default:
    external: true
volumes:
  data: null

