services:
  radarr:
    container_name: radarr
    hostname: radarr
    image: ghcr.io/hotio/radarr:release
    networks:
      - traefik_default
    ports:
      - 7878/tcp
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - /mnt:/mnt
      - /opt/appdata/radarr:/config
      - /opt/appdata/scripts:/scripts
      - /usr/bin/rclone:/usr/bin/rclone
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik_default
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.routers.radarr.rule=Host(`radarr.domain.com`)
      - traefik.http.services.radarr.loadbalancer.server.port=7878

networks:
  traefik_default:
    external: true


